name: scan with KICS

on:
  push:
    branches: [ master ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Mkdir kics
        # make sure results dir is created
        run: mkdir -p kics
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: "./Dockerfile"
          ignore_on_exit: results
          enable_comments: true
          output_path: ./results
          output_formats: json,html
          type: dockerfile
      - uses: actions/upload-artifact@v3
        with:
          name: results
          path: ./results
