name: scan with KICS

on:
  push:
    branches: [ master ]

jobs:
  kics-job:
    runs-on: ubuntu-latest
    name: kics-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Mkdir kics
        # make sure results dir is created
        run: mkdir -p kics
      - name: Run KICS Scan with SARIF result
        uses: checkmarx/kics-github-action@v1.7.0
        with:
          path: 'terraform'
          profiling: MEM
          output_path: kics
          output_formats: 'json,sarif'
      - name: Show results
        run: |
          cat kics/results.sarif
          cat kics/results.json
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: kics/results.sarif
